[project]
name = "doleus"
version = "0.2.2"
description = "Doleus: Test Your Image-based AI Models on Data Slices"
authors = [
    {name = "Hendrik Schulze Bröring"},
    {name = "Niklas Schmolenski"}
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.0.0,<3.0.0",
    "torchvision>=0.15.0,<1.0.0",
    "tqdm>=4.60.0,<5.0.0",
    "torchmetrics>=1.0.0,<2.0.0",
    "opencv-python-headless>=4.5.0,<5.0.0.0",
    "pytz>=2023.0",
    "numpy>=1.21.0,<3.0.0",
    "pillow>=10.0.0,<13.0.0"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pandas = "^2.3.0"
pycocotools = "^2.0.10"

