name: release

on:
  pull_request:
    types: [closed]
jobs:
  cd:
    permissions:
      id-token: write
      contents: write

    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Python Semantic Release to update CHANGELOG.md
        id: release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish: false
          commit: true
